[package]
name = "teggle-wasm2-storage"
version = "0.10.0"
authors = ["David Radunz <david@vimturian.ltd>", "Ethan Frey <ethanfrey@users.noreply.github.com>", "SCRT Labs <info@scrtlabs.com>"]
edition = "2018"
description = "WASM2 library with useful helpers for Storage patterns"
repository = "https://github.com/teggle-io/teggle-wasm2/tree/master/packages/storage"
license = "Apache-2.0"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[badges]
maintenance = { status = "actively-developed" }

[features]
# This enables iterator functionality, as exposed in wasm2-std/iterator
iterator = ["wasm2-std/iterator"]

[dependencies]
# Uses the path when built locally; uses the given version from crates.io when published
wasm2-std = { version = "0.10.0", package = "teggle-wasm2-std", path = "../std" }
serde = { version = "1.0.103", default-features = false, features = ["derive", "alloc"] }

[dev-dependencies]
snafu = { version = "0.6.3" }
